"""
Submission Validator
Checks artifacts against GECCO requirements.
"""

import os
from pathlib import Path
import sys

def validate_submission_package():
    print("=" * 60)
    print("SUBMISSION VALIDATION CHECKLIST")
    print("=" * 60)
    
    warnings = []
    errors = []
    
    root = Path(__file__).parent.parent
    
    # 1. Check Figures
    figures_dir = root / 'analysis' / 'figures'
    required_figures = [
        'figure1_aggregated_timeseries.pdf',
        'figure2_baseline_comparison.pdf'
        # 'figure3_failure_diagnostics.pdf',
        # 'figure4_carp_dynamics.pdf'
    ]
    
    print("\n[CHECK] Figures...")
    for fig in required_figures:
        path = figures_dir / fig
        if path.exists():
            print(f"  [OK] {fig} found")
            # TODO: Check file size / font embedding?
        else:
            print(f"  [MISSING] {fig}")
            errors.append(f"Missing Figure: {fig}")
            
    # 2. Check Documentation
    print("\n[CHECK] Documentation...")
    repro_dir = root / 'reproducibility_package'
    required_docs = [
        'README_REPLICATION.md',
        # 'APPENDIX_PARAMETERS.md' # Generated by scraper
    ]
    
    for doc in required_docs:
        path = repro_dir / doc
        if path.exists():
            print(f"  [OK] {doc} found")
        else:
            print(f"  [MISSING] {doc}")
            errors.append(f"Missing Doc: {doc}")
            
    # 3. Check Results Completeness
    print("\n[CHECK] Experimental Results...")
    results_dir = root / 'results' / 'baselines'
    if not results_dir.exists():
        print("  [FAIL] Results directory missing!")
        errors.append("Missing Results Directory")
    else:
        # Expect 4 baselines * 3 seeds = 12 summary JSONs
        # Plus 12 timeseries JSONs = 24 total
        json_files = list(results_dir.glob("*.json"))
        count = len(json_files)
        print(f"  Found {count} JSON result files.")
        
        # Core baseline check
        baselines = ['novelty_search', 'map_elites', 'random_search', 'fixed_constraints']
        seeds = [42, 123, 456]
        
        for base in baselines:
            for seed in seeds:
                fname = f"{base}_seed_{seed}.json"
                if not (results_dir / fname).exists():
                    print(f"  [MISSING] {fname}")
                    errors.append(f"Missing Result: {fname}")
                else:
                    pass # OK
                    
    # 4. Anonymization Check
    print("\n[CHECK] Anonymization...")
    forbidden_terms = ['Author Name', 'University of X', 'Anushka'] # Add actual name if known
    # Scan source files
    scan_dirs = [root / 'genesis_engine_v2', root / 'reproducibility_package']
    
    for sdir in scan_dirs:
        if not sdir.exists(): continue
        for r, d, f in os.walk(sdir):
            for file in f:
                if file.endswith(('.py', '.md', '.txt')):
                    try:
                        with open(Path(r)/file, 'r', encoding='utf-8', errors='ignore') as fobj:
                            content = fobj.read()
                            for term in forbidden_terms:
                                if term in content:
                                    print(f"  [WARN] Found '{term}' in {file}")
                                    warnings.append(f"Anonymity: '{term}' in {file}")
                    except Exception: 
                        pass
                    
    # Summary
    print("\n" + "=" * 60)
    print(f"VALIDATION COMPLETE: {len(errors)} Errors, {len(warnings)} Warnings")
    print("=" * 60)
    
    if errors:
        sys.exit(1)
    else:
        sys.exit(0)

if __name__ == '__main__':
    validate_submission_package()
